trap:
  zones: [0, 1, 2]
  interaction_zone: 0 # Zone that is adressed by the 729 Laser

routes:

  # single hop transitions
  - from: 1
    to: 0
    duration_us: 200
    heating:
      distribution: poisson
      mean: 1.0
    waveform_ref: waveforms/z1_to_z0.npy # placeholder

  - from: 0
    to: 1
    duration_us: 200
    heating:
      distribution: poisson
      mean: 1.0
    waveform_ref: waveforms/z0_to_z1.npy # placeholder

  - from: 1
    to: 2
    duration_us: 200
    heating:
      distribution: poisson
      mean: 1.0
    waveform_ref: waveforms/z1_to_z2.npy # placeholder
  
  - from: 2
    to: 1
    duration_us: 200
    heating:
      distribution: poisson
      mean: 1.0
    waveform_ref: waveforms/z2_to_z1.npy # placeholder

  # double hop transitions
  - from: 0
    to: 2
    duration_us: 450
    heating:
      distribution: poisson
      mean: 2.5
    waveform_ref: waveforms/z0_to_z2.npy # placeholder

  - from: 2
    to: 0
    duration_us: 450
    heating:
      distribution: poisson
      mean: 2.5
    waveform_ref: waveforms/z2_to_z0.npy # placeholder